[package]
name = "keyring-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "keyring_test"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
secrets_core = { path = "../core" }
